# Define named volumes for persistent data storage across container restarts

services:

  app:
    environment:
      - RAILS_PORT
      - RAILS_MASTER_KEY
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB_NAME
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
    build:
      context: .
    ports:
      - ${RAILS_PORT}:${RAILS_PORT}
    restart: on-failure
    develop:
      watch:
        - action: sync # Action sync is ideal for frameworks that support "Hot Reload" or equivalent functionality
          path: ./app
          target: /backend/app