services:
  app:
    image: jc21/nginx-proxy-manager:2.13.6
    restart: unless-stopped
    environment:

      # Postgres parameters
      DB_POSTGRES_HOST:
      DB_POSTGRES_PORT:
      DB_POSTGRES_USER:
      DB_POSTGRES_PASSWORD:
      DB_POSTGRES_NAME:
    ports:

      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port
    volumes:

      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:

      - db

  db:
    image: postgres:17
    environment:

      # Postgres parameters
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - ./postgresql:/var/lib/postgresql