# frozen_string_literal: true

source 'https://rubygems.org'

ruby file: '.ruby-version'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 8.1.1'

# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem 'propshaft'

# Use postgresql as the database for Active Record
gem 'pg'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Devise is a flexible authentication solution for Rails.
# It based on a modularity concept: use only what you really need.
# [https://github.com/heartcombo/devise]
gem 'devise'

# Simple, multi-client and secure token-based authentication for Rails.
# This gem refreshes the tokens on each request, and expires them in a short time, so the app is secure. Also, it
# maintains a session for each client/device, so you can have as many sessions as you want.
# [https://github.com/lynndylanhurley/devise_token_auth]
gem 'devise_token_auth'

# An admin engine for Rails applications.
# Abstracts common patterns to implement beautiful and elegant interfaces with ease.
# [https://activeadmin.info/]
gem 'activeadmin'

# Required for SCSS needed by active admin
gem 'sassc-rails'

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:windows, :jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem 'image_processing'

# ...
gem 'rack-cors'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: [:mri, :windows], require: 'debug/prelude'

  # Audits gems for known security defects (use config/bundler-audit.yml to ignore issues)
  gem 'bundler-audit', require: false

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem 'brakeman', require: false

  # RuboCop is a Ruby static code analyzer (a.k.a. linter) and code formatter
  # [https://github.com/rubocop/rubocop]
  gem 'rubocop', require: false
  gem 'rubocop-performance'
  gem 'rubocop-rails'

  # Add a comment summarizing the current schema
  gem 'annotate'

  # Gem suite for running tests
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'minitest', '~> 5.0'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'letter_opener'
  gem 'rails-erd'
  gem 'web-console'
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem 'capybara'
  gem 'selenium-webdriver'
end
