fragment Match on Match {
  date
  field {
    id
    maxSeats
  }
  id
  matchResult
  referee {
    ... on Referee {
      id
      firstName
      lastName
    }
  }
  round
  teams {
    ...Team
  }
  tournament {
    id
    name
    organizer {
      ... on Organizer {
        id
        firstName
        lastName
      }
    }
    sport {
      id
      description
      variantKind
    }
    court {
      id
      name
    }
  }
  winner {
    ...Team
  }
  viewers {
    ... on Player {
      id
    }
  }
  __typename
}
