query Me {
  me {
    ... on Organizer {
      id
      firstName
      lastName
      gender
      birthdate
      email
      __typename
    }
    ... on Player {
      id
      firstName
      lastName
      gender
      birthdate
      email
      joinedTournaments {
        ...Tournament
      }
      joinableTournaments {
        ...Tournament
      }
      bookedMatches {
        ...Match
      }
      matchesToPlay {
        ...Match
      }
      lostMatches {
        id
      }
      wonMatches {
        id
      }
      __typename
    }
    ... on Referee {
      id
      firstName
      lastName
      gender
      birthdate
      email
      refereedTournaments {
        ...Tournament
      }
      __typename
    }
  }
}
