# frozen_string_literal: true

Rails.application.routes.draw do
  # Devise also ships with default routes
  devise_for :users, controllers: {
    passwords:     'overrides/devise/passwords',
    confirmations: 'overrides/devise/confirmations',
    registrations: 'overrides/devise/registrations'
  }

  # Automatically added by running the active_admin:install generator
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Routes Integration for DeviseTokenAuth.
  # If you need to handle an authentication mechanism other than the basic mechanisms offered by the device, uncomment
  # this line and fix the route naming conflict with those generated by the device itself, if any.
  # This method is used to append the routes necessary for user authentication.
  # [https://devise-token-auth.gitbook.io/devise-token-auth/usage/routes]
  # mount_devise_token_auth_for 'User', at: 'api/auth'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end

  authenticated :user do
    root to: "tournaments#index", as: :authenticated_root
  end

  namespace :resources do
    # Views will be customized using the appropriate type (e.g., players). User controllers are primarily used to
    # integrate with the Devise workflow.
    resources :users do
      get 'homepage', to:'users#homepage'
      get 'profile', to: 'users#show'
      get 'unconfirmed', on: :new
      get 'passwords', on: :new
    end

  # Views will be customized using the appropriate type (e.g., players). UsersController is primarily used to
  # integrate with the Devise workflow, or to group actions common to all types of users.
  resource :user, only: [] do
    # Unauthenticated access points
    get :unconfirmed
    get :passwords

    # Authenticated access points
    get :profile
  end


  resources :tournaments, only: [:index, :new, :create, :show] do
    post 'subscribe', to: 'tournaments#subscribe'
    post 'unsubscribe', to: 'tournaments#unsubscribe'
  end
  resource :organizers, only: [:show]
  resource :referees, only: [:show]

  resources :matches do
    resources :results, only: [:index, :new, :create], :module => :matches
    resource :viewers_match, only: [:create, :destroy]
  end

  # specific route to show all matches that a user is subscribed to
  resources :players_tournaments, only: [:index], path: 'tournament_registrations'

  # == Endpoints for all user types
  # Defines singular resources for different user roles within the application.

  resource :player, only: [:show] do
    get :profile
  end

  resource :organizer, only: [:show] do
    get :profile
  end

  resource :referee, only: [:show] do
    get :profile
  end
end
