# frozen_string_literal: true

Rails.application.routes.draw do
  # Devise also ships with default routes
  devise_for :users, controllers: {
    passwords:     'resources/users_passwords',
    confirmations: 'resources/users_confirmations',
    registrations: 'resources/users_registrations'
  }

  # Routes Integration for DeviseTokenAuth.
  # If you need to handle an authentication mechanism other than the basic mechanisms offered by the device, uncomment
  # this line and fix the route naming conflict with those generated by the device itself, if any.
  # This method is used to append the routes necessary for user authentication.
  # [https://devise-token-auth.gitbook.io/devise-token-auth/usage/routes]
  # mount_devise_token_auth_for 'User', at: 'api/auth'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  namespace :resources do
    # Views will be customized using the appropriate type (e.g., players). User controllers are primarily used to
    # integrate with the Devise workflow.
    resources :users do
      get 'homepage', to:'users#homepage'
      get 'profile', to: 'users#show'
      get 'unconfirmed', on: :new
      get 'passwords', on: :new
    end


    resources :tournaments, only: [:index, :new, :create, :show]
  end

  resource :organizers, only: [:show]
  resource :referees, only: [:show]
  resources :homepage


  resources :matches do
    resources :results, only: [:index, :new, :create], :module => :matches
  end

  resources :player_tournaments, only: [:index, :show], path: 'tournament_registrations' do
    member do
      delete :unsubscribe
    end
  end

end
