# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # Devise also ships with default routes
  devise_for :users, controllers: {
    passwords:     'overrides/devise/passwords',
    confirmations: 'overrides/devise/confirmations',
    registrations: 'overrides/devise/registrations'
  }

  # Automatically added by running the active_admin:install generator
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Routes Integration for DeviseTokenAuth.
  # If you need to handle an authentication mechanism other than the basic mechanisms offered by the device, uncomment
  # this line and fix the route naming conflict with those generated by the device itself, if any.
  # This method is used to append the routes necessary for user authentication.
  # [https://devise-token-auth.gitbook.io/devise-token-auth/usage/routes]
  # mount_devise_token_auth_for 'User', at: 'api/auth'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # == Authentication Endpoints
  # Defining endpoints for authenticated and unauthenticated users

  # Redirect unauthenticated users to the login page
  unauthenticated do
    as :user do
      root to: 'devise/sessions#new'
    end
  end

  # Direct the user to their specific dashboard and name the path
  [:player, :organizer, :referee].each do |role|
    authenticated(:user, proc { it.is_a? "User::#{role.to_s.camelize}".constantize }) do
      root to: "#{role}s#show", as: "authenticated_#{role}"
    end
  end

  # Views will be customized using the appropriate type (e.g., players). UsersController is primarily used to
  # integrate with the Devise workflow, or to group actions common to all types of users.
  resource :user, only: [] do
    # Instructions for devise mailers
    get :unconfirmed
    get :passwords

    # The profile is shared between all user types
    get :profile
  end

  # == Endpoints for all user types
  # Defines singular resources for different user roles within the application.

  resource :player, only: [:show] do
    resources :tournaments, only: [:show], module: :players do
      post :join, to: 'tournaments#join'
    end

    resources :matches, only: [:index], module: :players do
      get :joined, on: :collection

      post :book, to: 'matches#book'
      post :unbook, to: 'matches#unbook'
    end

    get :registrations

    get :profile
  end

  resource :organizer, only: [:show] do
    resources :tournaments, only: [:new, :create], module: :organizers
    get :profile
  end

  resource :referee, only: [:show] do
    resources :matches, only: [:new, :create], module: :referees

    get :profile
  end
end

# ORGANIZER
# organizer fa login
#   - arriva alla sua homepage
#     - dentro la homepage c'è il bottone per creare un tournament
#       - dentro la pagine di creazione c'è il form classico con crea + cancel
#   - navbar:
#     - homepage
#     - create tournament
#     - profile

# REFEREE
# referre fa login
#   - arriva alla sua homepage
#     - dentro alla sua homempage vede una lista di match dei tornei a cui è iscritto l'arbitro e che arbitra effettivamente
#       - per ogni match può inserire i risultati
#   - navbar:
#     - homepage
#     - profile

# PLAYER
# player fa login
#   - arriva alla sua homepage
#     - dentro alla sua homepage vede la lista di tornei
#       - filtro per i tornei
#       - per ogni tornei c'è il dettaglio
#           - il dettaglio del torneo ha un bottone per registrarsi (eligible)
#           - se è un torneo a team ci sono i join per team
#   - navbar:
#     - homepage
#     - spectate -> book / unbook pages
#     - booked matches
#     - profile

# NOTE
#   - Quando il torneo ha gli slot riempiti:
#       - la fase di registrazione si chiude in automatico e vengono creati i match
#       - vengono creati i team
#       - vengono distribuiti gli arbitri sui match
